# VENTANA

ANCHO_VENTANA = 1200
ALTO_VENTANA = 800
FPS = 60

# COLORES

BLANCO = (255, 255, 255)
AZUL = (0, 0, 102)
NEGRO = (0, 0, 0)

# JUGADOR

ANCHO_JUGADOR = 64
ALTO_JUGADOR = 64
PUNTOS_SALUD_JUGADOR = 100
VIDAS_JUGADOR = 3
VELOCIDAD_JUGADOR = 10
BALA_VELOCIDAD_JUGADOR = 30
ANCHO_BALA_JUGADOR = 15
ALTO_BALA_JUGADOR = 15

# ENEMIGO 1
ANCHO_ENEMIGO1 = 140
ALTO_ENEMIGO1 = 140
PUNTOS_SALUD_ENEMIGO1 = 50
VELOCIDAD_ENEMIGO1 = 'N/A'
BALA_VELOCIDAD_ENEMIGO1 = 10
TIEMPO_ENTRE_DISPAROS_ENEMIGO1 = 4
ANCHO_BALA_ENEMIGO1 = 100
ALTO_BALA_ENEMIGO1 = 100
PUNTOS_AL_DERROTAR = 50

# ENEMIGO 2
ANCHO_ENEMIGO2 = 80
ALTO_ENEMIGO2 = 80
VELOCIDAD_ENEMIGO2 = 4
BALA_VELOCIDAD_ENEMIGO2 = 'N/A'
TIEMPO_ENTRE_DISPAROS_ENEMIGO2 = 'N/A'
ANCHO_BALA_ENEMIGO2 = 'N/A'
ALTO_BALA_ENEMIGO2 = 'N/A'

# ENEMIGO 3
ANCHO_ENEMIGO3 = 50
ALTO_ENEMIGO3 = 50
VELOCIDAD_ENEMIGO3 = 'N/A'
BALA_VELOCIDAD_ENEMIGO3 = 'N/A'
TIEMPO_ENTRE_DISPAROS_ENEMIGO3 = 'N/A'
ANCHO_BALA_ENEMIGO3 = 'N/A'
ALTO_BALA_ENEMIGO3 = 'N/A'

# BONUS1 - CORAZÓN
ANCHO_BONUS1 = 50
ALTO_BONUS1 = 50